// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Susmeter.Ef;

namespace Susmeter.Ef.Migrations
{
    [DbContext(typeof(SusmeterDbContext))]
    partial class SusmeterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("Susmeter.Ef.Entities.ColorEntity", b =>
                {
                    b.Property<string>("HexCode")
                        .HasColumnType("TEXT")
                        .HasMaxLength(7);

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.HasKey("HexCode");

                    b.ToTable("Color");

                    b.HasData(
                        new
                        {
                            HexCode = "#C51111",
                            ColorName = "Red"
                        },
                        new
                        {
                            HexCode = "#132ED1",
                            ColorName = "Blue"
                        },
                        new
                        {
                            HexCode = "#117F2D",
                            ColorName = "Green"
                        },
                        new
                        {
                            HexCode = "#ED54BA",
                            ColorName = "Pink"
                        },
                        new
                        {
                            HexCode = "#EF7D0E",
                            ColorName = "Orange"
                        },
                        new
                        {
                            HexCode = "#F6F658",
                            ColorName = "Yellow"
                        },
                        new
                        {
                            HexCode = "#3F474E",
                            ColorName = "Black"
                        },
                        new
                        {
                            HexCode = "#D6E0F0",
                            ColorName = "White"
                        },
                        new
                        {
                            HexCode = "#6B31BC",
                            ColorName = "Purple"
                        },
                        new
                        {
                            HexCode = "#71491E",
                            ColorName = "Brown"
                        },
                        new
                        {
                            HexCode = "#38FEDB",
                            ColorName = "Cyan"
                        },
                        new
                        {
                            HexCode = "#50EF39",
                            ColorName = "Lime"
                        });
                });

            modelBuilder.Entity("Susmeter.Ef.Entities.MatchEntity", b =>
                {
                    b.Property<long>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<byte>("Winner")
                        .HasColumnType("INTEGER");

                    b.HasKey("MatchId");

                    b.ToTable("Match");
                });

            modelBuilder.Entity("Susmeter.Ef.Entities.MatchPlayerEntity", b =>
                {
                    b.Property<long>("MatchPlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("HexColor")
                        .HasColumnType("TEXT");

                    b.Property<long>("MatchId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("PlayerRole")
                        .HasColumnType("INTEGER");

                    b.HasKey("MatchPlayerId");

                    b.HasIndex("HexColor");

                    b.HasIndex("MatchId");

                    b.HasIndex("PlayerId");

                    b.ToTable("MatchPlayer");
                });

            modelBuilder.Entity("Susmeter.Ef.Entities.PlayerEntity", b =>
                {
                    b.Property<long>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarHexColor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.HasKey("PlayerId");

                    b.HasIndex("AvatarHexColor");

                    b.ToTable("Player");

                    b.HasData(
                        new
                        {
                            PlayerId = 1L,
                            AvatarHexColor = "#F6F658",
                            Name = "Blaž",
                            Nickname = "not knupli"
                        },
                        new
                        {
                            PlayerId = 2L,
                            AvatarHexColor = "#ED54BA",
                            Name = "Lara",
                            Nickname = "Meronja"
                        },
                        new
                        {
                            PlayerId = 3L,
                            AvatarHexColor = "#50EF39",
                            Name = "Tancer",
                            Nickname = "c00kie"
                        },
                        new
                        {
                            PlayerId = 4L,
                            AvatarHexColor = "#71491E",
                            Name = "Roki",
                            Nickname = "thefk69"
                        },
                        new
                        {
                            PlayerId = 5L,
                            AvatarHexColor = "#3F474E",
                            Name = "Kevin",
                            Nickname = "Krušni oče"
                        },
                        new
                        {
                            PlayerId = 6L,
                            AvatarHexColor = "#D6E0F0",
                            Name = "Eagle",
                            Nickname = "Eagle"
                        },
                        new
                        {
                            PlayerId = 7L,
                            AvatarHexColor = "#132ED1",
                            Name = "Dani",
                            Nickname = "Bani"
                        },
                        new
                        {
                            PlayerId = 8L,
                            AvatarHexColor = "#38FEDB",
                            Name = "Valerija",
                            Nickname = "Val"
                        },
                        new
                        {
                            PlayerId = 9L,
                            AvatarHexColor = "#117F2D",
                            Name = "Jure",
                            Nickname = "Jure"
                        },
                        new
                        {
                            PlayerId = 10L,
                            AvatarHexColor = "#6B31BC",
                            Name = "Arijan",
                            Nickname = "Archie"
                        });
                });

            modelBuilder.Entity("Susmeter.Ef.Entities.MatchPlayerEntity", b =>
                {
                    b.HasOne("Susmeter.Ef.Entities.ColorEntity", "Color")
                        .WithMany()
                        .HasForeignKey("HexColor");

                    b.HasOne("Susmeter.Ef.Entities.MatchEntity", "Match")
                        .WithMany("Players")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Susmeter.Ef.Entities.PlayerEntity", "Player")
                        .WithMany("Matches")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Susmeter.Ef.Entities.PlayerEntity", b =>
                {
                    b.HasOne("Susmeter.Ef.Entities.ColorEntity", "AvatarColor")
                        .WithMany()
                        .HasForeignKey("AvatarHexColor");
                });
#pragma warning restore 612, 618
        }
    }
}
